version: "3"

services:
  api:
    build: .
    container_name: 'api-container'
    command: python main.py
    env_file:
      - .env
    restart: always
    ports:
      - 8080:80
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres-container'
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'